### ISSUE TITLE
Feature request: Warn if model's first layer is not on a plane

### ISSUE THREAD

**Issue by probonopd** [prusa3d/PrusaControl#27]
If the user loads a file similar to this, then there should be a warning, saying that this will not print correctly and will result in "filament spaghetti". In this case, the rectangular area in the second picture will not have bed adhesion.

First layer:

![screenshot_20170717_200851](https://user-images.githubusercontent.com/2480569/28282786-ff5c47aa-6b2b-11e7-8113-960d69cc8a21.png)

Second layer:

![screenshot_20170717_200950](https://user-images.githubusercontent.com/2480569/28282788-00539b54-6b2c-11e7-97fa-8f9d07f8a7cc.png)

**Comment by tibor-vavra** [comment]
You can turn on Analysis module in Settings->PrusaControl settings. Its check your scene every time you change it for basic mistakes. At this moment, it is sometimes slow, thats why its turn off at default.
