### ISSUE TITLE
Failed to execute Scrpit Main / PrusaControl 0.9.3_384_beta

### ISSUE THREAD

**Issue by Stevuh** [prusa3d/PrusaControl#45]
I installed the new PrusaControl 0.9.3_384_beta and then i got the Error "Failed to execute Main".
It worked with the Version before this.
I Attach the Log file.

[prusacontrol.zip](https://github.com/prusa3d/PrusaControl/files/1306157/prusacontrol.zip)

**Comment by tibor-vavra** [comment]
Hi,

Yes, I found this problem too.

As a workaround you can do this:

Download new configuration files from github.com/prusa3d/
prusacontrol-settings and place them to .prusacontrol folder.

Dne 15. 9. 2017 13:14 napsal uživatel "Stevuh" <notifications@github.com>:

**Comment by Stevuh** [comment]
Hi,

I Downloaded and placed it in .prusacontrol folder.
But that didnt worked.

Log file below.
[prusacontrol.zip](https://github.com/prusa3d/PrusaControl/files/1306191/prusacontrol.zip)

**Comment by marcopiraccini** [comment]
I have the same problem (Ubuntu 16.04). Fixed putting the files in `~/.prusacontrol/data/`

**Comment by Stevuh** [comment]
@marcopiraccini that didnt worked for me :/  .
Hope tibor finds a Solution.

**Comment by MarkFortun** [comment]
I am also receiving this issue, and I have tried replacing the files as tibor suggested, but am still receiving the issue. 
-Windows 10

**Comment by tibor-vavra** [comment]
Can you write me your system version and tree of files in .prusacontrol folder?

**Comment by Hewster** [comment]
Got it working, I did this (NOTE: This is on Windows 10):

Downloaded the latest version of PrusaControl(0.9.3.388_beta) from here:
https://prusacontrol.org/#download

Downloaded the latest settings in a zip file from here:
https://github.com/prusa3d/PrusaControl-settings

Pasted the extracted new files here (overwriting existing):
C:\Program Files (x86)\PrusaControl\data

Ran the program, but still not working.

So I then  pasted the new files in:
C:\Users\[**USER NAME**]\.prusacontrol

Ran the program and it worked !

I then uninstalled PrusaControl, and deleted the remaining folders:

C:\Program Files (x86)\PrusaControl
C:\Users\[**USER NAME**]\.prusacontrol

Then installed the latest version again, and it worked straight away :)

So maybe users with this problem simply need to copy the new settings files into their C:\Users\[**USER NAME**]\.prusacontrol folder
or
Uninstall and delete the remaining folders before re-installing.

HTH
Hewster

**Comment by Stevuh** [comment]
Hello @tibor-vavra,

I am using Windows 10 Home Edition 64-Bit.
Here are the files in my .prusacontrol Folder.

[Files.zip](https://github.com/prusa3d/PrusaControl/files/1309019/Files.zip)

**Comment by Stevuh** [comment]
Hi @ all

I found a Solution and now its working.
I Uninstall Prusa Control and then i searched for "prusacontrol" Folders and deleted all Folders.
Then i run regedit and there i was searching for "prusacontrol" and deleted the Prusacontrol.
Then i restartet my Pc and installed it.

Now it is working.

**Comment by tibor-vavra** [comment]
Hi @Stevuh,

Iam glad you find solution, today we release new version 0.9.3.390, where this problems are gone. But part of code for updating of printing settings has to be redesigned in future. 

I looked to files(Files.zip), what you attached to your previous post, and inside were .html files named as printing .json settings files. I tought you will download it by download button on github website. Sorry for I didnt tell you that.
![image](https://user-images.githubusercontent.com/4319021/30545032-baef188e-9c88-11e7-9361-bcac97f9581e.png)
