### ISSUE TITLE
PrusaControl pollutes Windows home directory

### ISSUE THREAD

**Issue by themaninthesuitcase** [prusa3d/PrusaControl#58]
On Windows installs PrusaControl saves a lot of files into the home directory. On Linux and OSX these files are saved to more appropriate locations which are hidden from the user in general use.

I propose that user files are added to the %appdata% folder which is the normal location for these sorts of files.

## Problem files/folders
* .prusacontrol
* printrunconf.ini
* prusacontrol.cfg

Ideally `prusacontrol.log` would also be relocated but I understand PC is still currently in beta so this isn't as important.

**Comment by bubnikv** [comment]
On Windows, Slic3r puts its configuration into
"C:\Users\your_user_name\AppData\Roaming\Slic3r"
or "C:\Documents and Settings\your_user_name\Application Data\Slic3r"
Maybe PrusaControl could use the same approach?
