### ISSUE TITLE
Generating G-code preview hangs or takes incredible long time

### ISSUE THREAD

**Issue by ImreZol** [prusa3d/PrusaControl#71]
I try to slice the Track.stl from https://www.thingiverse.com/thing:1385312 with default settings.

After slicing, the G-code generration hangs.
Prusa Control is running and responding (I can cancel the operation). It's use ~90% CPU (I think it means  use 1 core). I gave up after an hour...

With Slic3r Prusa Editon 1.38.6-prusa3d it (slicing and G-code export) succeed within 1-2 minutes (with default settings).

Prusa Control Ver0.9.4_415_beta (Slic3r engine ver:1.37.2.1-prusa3d)
Printer: mk2s
Material: Prusa PLA
Quality: Optimal -0.15 mm
Infill: Standard - 20%
Support: None
Brim: Off

Os Ver: MacOS High Sierra 10.13.2
Computer: MacBook Pro(15-inch,2016) 
Processor 2,6 Ghz Intel Core i7
Memory: 16 GB

**Comment by jsgraves22** [comment]
Same issue for me with 415.  Similar MacBook.  G-code generation hangs at 100% and I'm never able to save it.  I have waited nearly an hour and it drains my MacBooks battery like a champ but never generates.  Slic3r works fine.

**Comment by cdburgess** [comment]
I am experiencing the same issues. So I upgraded to HighSierra 10.13.3 and I am still getting the same issues. I do think it's hit and miss. One of the jobs I was working on finally shows the `Save G-Code` button. But it was quite a while after it hit 100%.

Prusa Control Ver0.9.4_415_beta (Slic3r engine ver:1.37.2.1-prusa3d)
Printer: MK3
Material: Prusa PLA
Quality: Optimal -0.15 mm
Infill: Standard - 20%
Support: None
Brim: Off

Os Ver: MacOS High Sierra 10.13.3
Computer: Mac mini (Late 2012)
Processor 2.3 GHz Intel Core i7
Memory: 16 GB 1600 MHz DDR3

**Comment by cdburgess** [comment]
I did discover that if there are possible issues with the model, it will never finish. I have some small objects I am trying to print multiples of. When I only do a few, the g-code button will appear. But I can tell there's a problem with the model because not all the layers are there when I drag the layer viewer up and down. After repairing the model, it will eventually finish and I can export the g-code.

**Comment by cknowles2112** [comment]
doing some more research - even with known good models, things can take an insanely long time.  But, if I scale the model down to 20% of size, it takes MUCH less time.  All of this is in comparison to S3D's timing.  I think there's a correlation between volume of the model, and the time that the g-code preview generation takes.

**Comment by joelkoz** [comment]
Just happened to me also.  Macbook Pro, 16 GB RAM, High Sierra 10.13.3

**Comment by ldestrooper** [comment]
Also just had this issue with PrusaControl 0.9.4_415_beta on macOS High Sierra 10.13.3

**Comment by magnumuk** [comment]
This has been a problem for several months now, I wonder why no fix has been issued yet?

**Comment by leewrigh7** [comment]
Same problem here,  attempting to print thing:19104 (thingverse)...

Stuck at 100%, therefore can't save to SD or print.

2014 Macbook pro, 16GB, High Sierra 10.13.3, Latest PrusaControl (as of 30th March 2018).

Prusa PLA, 0.15mm, Solid, Support: none, Brim:off

**Comment by knot2nice** [comment]
still a problem for me as well...sigh

**Comment by maximlevitsky** [comment]
Same here on Linux. Seems to work fast enough in Win10 on same machine. Didn't test rigoursly though.
Maybe this is somehow OpenGL related?

**Comment by JoschaMiddendorf** [comment]
im having the same problem

**Comment by magnumuk** [comment]
It looks like the only platform that is being supported is Windows, nothing for Mac and Linux users.

**Comment by buffedelic** [comment]
mee too, MacOS 10.13.4 and latest PrusaControl. Smaller objects slices with no significant problem but larger more complex models just keep spinning until I run cmd-q and fire upp slic3r

**Comment by hosek** [comment]
I have same issue, but regarding the status bar, problem is probably not in generation gcode itself, but generating G-code preview. Just thought - is there some condition, that save gcode button is shown only after preview is ready? Then if preview somehow crash or take too long for complex objects, user will never see the saving button even the gcode file is ready.

**Comment by magnumuk** [comment]
This problem has been around for some time now.  I would have expected a fix by now! I wonder if anyone is actually working on the problem?

**Comment by Ahbrown41** [comment]
Same issue, S3D is so fast, this is terribly slow.

**Comment by workinghard** [comment]
Same observation here. MacOS most recent version. gcode is getting generated but the preview of the gcode is not possible for more complex objects. Because you can't save it, PrusaControl can't be used this way at all :(

**Comment by alhazar313** [comment]
I have the same issue, the status bar gets right near the end and stops pegging the cpu @90%, its concerning that it seems this issue isn't being addressed or acknowledged....

**Comment by frenchrabbit** [comment]
Same. For some stl if I wait for 20minutes it gives preview and allowing to save , sometimes it never appears. So every print preparation is like lottery.

**Comment by gavztheouch** [comment]
just tried again and like another member it looks like scaling down the models to say 20%  seems to work. Maybe its the code that creates an estimate time for the g-code to run as slic3er does not have this feature and also works ok.

**Comment by workinghard** [comment]
@hosek : Printing a gcode without checking it, is not an option! Of course you could use any online tools for checking but this miss the point of PrusaControl completely. It supposed to be simple, so my wife can load, preview and print. If that doesn't work, it missed his target and will not be used. I see this bug as pretty urgent and major for this project. But it looks like there are no resources available right now

**Comment by buffedelic** [comment]
I agree with @hosek, preview of gcode is cruzial to determine if print will be good or not. Especially when using supports.

The ease of use whas really appealing to me when learning my kids the basics. Now they had to learn the hard way :) lots of profiles made for various situations

**Comment by hosek** [comment]
@workinghard yes, I agree with you. It wasn't supposed to be solution it's just temporary workaround for people who want to use easy UI of Prusa Control, but are able to check gcode somewhere else... just to know that it's possible. Sorry if it was not clear from my post.

**Comment by joelkoz** [comment]
Update: This is definitely an issue with SLOW gcode preview generation, and not locking up entirely.  I had a very large model that seemed to "get stuck" on gcode preview generation. It was late at night and I gave up after 30 minutes of waiting, but I did NOT stop the process and I just went to bed.  When I came back in the morning, the preview was available and the save worked as normal.

**Comment by WarrenSchultz** [comment]
I have a question on this, as I'm also experiencing this issue. I've tried exporting the gcode locally as well as sending direct to the printer. (Octoprint on RPi 3B+)

The final gcode generation does not seem to be multithreaded, or if it is, it isn't utilizing all cores. 
How is generation currently handled? Serially by object, or by layer? (or?)

Would it be possible to create volumes around each object on the plate, and then launch separate threads for code generation per object before re-merging the code? (I understand this may be a naive request, since I don't know how that code works under the hood).

**Comment by AnatolLocker** [comment]
Looks like this problem isn’t high on the developers list...

**Comment by ImreZol** [comment]
Because Slic3r PE will become the PrusaControl 2 (https://www.prusaprinters.org/prusa-research-summer-update-2018) I close this issue...

**Comment by MartinMajewski** [comment]
How can you close this issue if it is a nagging problem for all slic3r PE users on a Mac?! I use the most current version (1.41.2-rc+) and have had this issues for months now. So it is a problem with the current development branch of slic3r. I pledge for reopening this issue and really have a look at it. Exporting gcode / sending gcode to OctoPrint is no fun at all at the moment!

**Comment by ImreZol** [comment]
Hi Martin,

This issue was about PrusaControl not Slic3r.
I closed this issue, because prusa no longer develop this project (the last commit was  on Jan 5, 2018).

I am not a contributor just a simple user, but I think if you have this problem with Slic3r, you should open a ticket in Slic3r project repo: 
- Slic3r -> Help -> Report an Issue 
- or  use this link: https://github.com/prusa3d/slic3r/issues/new

I do not have this problem with Slic3r PE 1.41.2+, so you should try this version at first.
(I have 10.14.1 Mojave on my Mac)

**Comment by psavva** [comment]
Unchecking "Avoid Crossing Parameters" makes the lag go away.

**Comment by handell** [comment]
The new PrusaSlicer fixed the issue. THANKS!
